// models/Exam.js
// Mongoose model for storing exam sessions including user details, questions, answers, and Gemini validations

const mongoose = require("mongoose");

const examSchema = new mongoose.Schema({
  fullName: {
    type: String,
    required: true,
    trim: true,
  },
  email: {
    type: String,
    required: true,
    unique: true, // Assuming emails are unique across exams; adjust if needed
    lowercase: true,
    trim: true,
  },
  phone: {
    type: String,
    required: true,
    trim: true,
  },
  college: {
    type: String,
    required: true,
    trim: true,
  },
  questions: [
    {
      type: String,
      required: true,
    },
  ], // Array of 3 Python questions generated by Gemini
  answers: [
    {
      type: String,
      default: "", // User's responses; can be empty if not submitted yet
    },
  ], // Array of 3 user answers, in order matching questions
  validations: [
    {
      isCorrect: {
        type: Boolean,
        default: false,
      },
      score: {
        type: Number,
        min: 0,
        max: 10,
        default: 0,
      },
      feedback: {
        type: String,
        default: "",
      },
    },
  ], // Gemini validation results for each answer; populated after submission
  totalScore: {
    type: Number,
    min: 0,
    max: 10,
    default: 0,
  }, // Overall scaled score (0-10)
  status: {
    type: String,
    enum: [
      "registered",
      "questions_generated",
      "answers_submitted",
      "validated",
    ],
    default: "registered",
  },
  neuralPatterns: {
    type: String,
    default: "Analyzed and recorded in quantum database.", // Fun placeholder from UI
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

// Index for efficient queries
examSchema.index({ "user.email": 1 });
examSchema.index({ createdAt: -1 });

// Pre-save middleware to update timestamp
examSchema.pre("save", function (next) {
  this.updatedAt = Date.now();
  next();
});

module.exports = mongoose.model("Exam", examSchema);
